export const routePaths = {
  public: {
    home: "/",
  },
  auth: {
    login: "/login",
    signup: "/signup",
  },
  dashboard: {
    home: "/dashboard",
    requests: "/requests",
    createRequest: "/requests/create",
    myRequests: "/requests/my-requests",
    employeeRequests: "/requests/employee-requests",
    merchantRequests: "/requests/merchant-requests",
    pendingApprovals: "/requests/pending-approvals",
    fulfillmentQueue: "/requests/fulfillment-queue",
    myAssets: "/my-assets",
    assets: "/inventory/assets",
    transfers: "/inventory/transfers",
    returns: "/inventory/returns",
    history: "/inventory/history",
    inventory: "/inventory",
    products: "/products",
    merchants: "/merchants",
    warehouses: "/warehouses",
    members: "/members",
    roles: "/roles",
    settings: "/settings",
    notifications: "/notifications",
    spaces: "/spaces",
    joinRequests: "/join-requests",
    workflows: "/workflows",
    auditLogs: "/audit-logs",
  },
} as const;
