const ASSET_REQUEST_STATUS = {
  PENDING: "PENDING",
  MANAGER_APPROVED: "MANAGER_APPROVED",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  CANCELLED: "CANCELLED",
  FULFILLED: "FULFILLED",
};

const ASSET_REQUEST_PRIORITY = {
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
  CRITICAL: "CRITICAL",
};

const ASSET_REQUEST_PERMISSIONS = {
  CREATE_ASSET_REQUEST: "CREATE_ASSET_REQUEST",
  VIEW_ASSET_REQUEST: "VIEW_ASSET_REQUEST",
  MANAGER_APPROVE_ASSET_REQUEST: "MANAGER_APPROVE_ASSET_REQUEST",
  IT_APPROVE_ASSET_REQUEST: "IT_APPROVE_ASSET_REQUEST",
  REJECT_ASSET_REQUEST: "REJECT_ASSET_REQUEST",
  CANCEL_ASSET_REQUEST: "CANCEL_ASSET_REQUEST",
  FORWARD_ASSET_REQUEST: "FORWARD_ASSET_REQUEST",
};

module.exports = {
  ASSET_REQUEST_STATUS,
  ASSET_REQUEST_PRIORITY,
  ASSET_REQUEST_PERMISSIONS,
};