const ASSET_REQUEST_STATUS = {
  PENDING_MANAGER: "PENDING_MANAGER",
  PENDING_IT: "PENDING_IT",
  PENDING_ZONAL: "PENDING_ZONAL",
  PENDING_FULFILLMENT: "PENDING_FULFILLMENT",
  FULFILLMENT_DELAYED: "FULFILLMENT_DELAYED",
  PARTIALLY_FULFILLED: "PARTIALLY_FULFILLED",
  REJECTED: "REJECTED",
  FULFILLED: "FULFILLED",
  OUT_OF_STOCK: "OUT_OF_STOCK",
  PROCUREMENT_REQUIRED: "PROCUREMENT_REQUIRED",
  PENDING_ZONAL_MANAGER: "PENDING_ZONAL",
  FULFILLMENT_PENDING: "PENDING_FULFILLMENT",
  APPROVED: "PENDING_FULFILLMENT",
  CANCELLED: "REJECTED",
  PENDING: "PENDING_MANAGER",
  MANAGER_APPROVED: "PENDING_IT",
};

const LEGACY_ASSET_REQUEST_STATUS_MAP = {
  PENDING_ZONAL_MANAGER: ASSET_REQUEST_STATUS.PENDING_ZONAL,
  FULFILLMENT_PENDING: ASSET_REQUEST_STATUS.PENDING_FULFILLMENT,
  APPROVED: ASSET_REQUEST_STATUS.PENDING_FULFILLMENT,
  CANCELLED: ASSET_REQUEST_STATUS.REJECTED,
};

const ASSET_REQUEST_STATUS_VALUES = [
  ...new Set([
    ...Object.values(ASSET_REQUEST_STATUS),
    ...Object.keys(LEGACY_ASSET_REQUEST_STATUS_MAP),
  ]),
];

const normalizeAssetRequestStatus = (status) =>
  LEGACY_ASSET_REQUEST_STATUS_MAP[status] || status;

const ASSET_REQUEST_TYPE = {
  EMPLOYEE_ASSET: "EMPLOYEE_ASSET",
  MERCHANT_ASSET: "MERCHANT_ASSET",
};

const ASSET_REQUEST_STEP_KEYS = {
  MANAGER_APPROVAL: "MANAGER_APPROVAL",
  IT_APPROVAL: "IT_APPROVAL",
  ZONAL_APPROVAL: "ZONAL_APPROVAL",
  FULFILLMENT: "FULFILLMENT",
  ZONAL_MANAGER_APPROVAL: "ZONAL_APPROVAL",
  WAREHOUSE_FULFILLMENT: "FULFILLMENT",
};

const ASSET_REQUEST_APPROVAL_ACTIONS = {
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
};

const ASSET_REQUEST_PRIORITY = {
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
  CRITICAL: "CRITICAL",
};

const ASSET_REQUEST_PERMISSIONS = {
  CREATE_ASSET_REQUEST: "CREATE_ASSET_REQUEST",
  VIEW_ASSET_REQUEST: "VIEW_ASSET_REQUEST",
  APPROVE_ASSET_REQUEST: "APPROVE_ASSET_REQUEST",
  FULFILL_ASSET_REQUEST: "FULFILL_ASSET_REQUEST",
  MANAGER_APPROVE_ASSET_REQUEST: "MANAGER_APPROVE_ASSET_REQUEST",
  IT_APPROVE_ASSET_REQUEST: "IT_APPROVE_ASSET_REQUEST",
  ZONAL_MANAGER_APPROVE_ASSET_REQUEST: "ZONAL_MANAGER_APPROVE_ASSET_REQUEST",
  WAREHOUSE_FULFILL_ASSET_REQUEST: "WAREHOUSE_FULFILL_ASSET_REQUEST",
  REJECT_ASSET_REQUEST: "REJECT_ASSET_REQUEST",
  CANCEL_ASSET_REQUEST: "CANCEL_ASSET_REQUEST",
  FORWARD_ASSET_REQUEST: "FORWARD_ASSET_REQUEST",
};

module.exports = {
  ASSET_REQUEST_STATUS,
  ASSET_REQUEST_STATUS_VALUES,
  LEGACY_ASSET_REQUEST_STATUS_MAP,
  normalizeAssetRequestStatus,
  ASSET_REQUEST_TYPE,
  ASSET_REQUEST_PRIORITY,
  ASSET_REQUEST_STEP_KEYS,
  ASSET_REQUEST_APPROVAL_ACTIONS,
  ASSET_REQUEST_PERMISSIONS,
};
