const ASSET_REQUEST_STATUS = {
  PENDING_MANAGER: "PENDING_MANAGER",
  PENDING_IT: "PENDING_IT",
  PENDING_ZONAL_MANAGER: "PENDING_ZONAL_MANAGER",
  FULFILLMENT_PENDING: "FULFILLMENT_PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  CANCELLED: "CANCELLED",
  FULFILLED: "FULFILLED",
  PENDING: "PENDING_MANAGER",
  MANAGER_APPROVED: "PENDING_IT",
};

const ASSET_REQUEST_TYPE = {
  EMPLOYEE_ASSET: "EMPLOYEE_ASSET",
  MERCHANT_ASSET: "MERCHANT_ASSET",
};

const ASSET_REQUEST_STEP_KEYS = {
  MANAGER_APPROVAL: "MANAGER_APPROVAL",
  IT_APPROVAL: "IT_APPROVAL",
  ZONAL_MANAGER_APPROVAL: "ZONAL_MANAGER_APPROVAL",
  WAREHOUSE_FULFILLMENT: "WAREHOUSE_FULFILLMENT",
};

const ASSET_REQUEST_APPROVAL_ACTIONS = {
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
};

const ASSET_REQUEST_PRIORITY = {
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
  CRITICAL: "CRITICAL",
};

const ASSET_REQUEST_PERMISSIONS = {
  CREATE_ASSET_REQUEST: "CREATE_ASSET_REQUEST",
  VIEW_ASSET_REQUEST: "VIEW_ASSET_REQUEST",
  APPROVE_ASSET_REQUEST: "APPROVE_ASSET_REQUEST",
  FULFILL_ASSET_REQUEST: "FULFILL_ASSET_REQUEST",
  MANAGER_APPROVE_ASSET_REQUEST: "MANAGER_APPROVE_ASSET_REQUEST",
  IT_APPROVE_ASSET_REQUEST: "IT_APPROVE_ASSET_REQUEST",
  ZONAL_MANAGER_APPROVE_ASSET_REQUEST: "ZONAL_MANAGER_APPROVE_ASSET_REQUEST",
  WAREHOUSE_FULFILL_ASSET_REQUEST: "WAREHOUSE_FULFILL_ASSET_REQUEST",
  REJECT_ASSET_REQUEST: "REJECT_ASSET_REQUEST",
  CANCEL_ASSET_REQUEST: "CANCEL_ASSET_REQUEST",
  FORWARD_ASSET_REQUEST: "FORWARD_ASSET_REQUEST",
};

module.exports = {
  ASSET_REQUEST_STATUS,
  ASSET_REQUEST_TYPE,
  ASSET_REQUEST_PRIORITY,
  ASSET_REQUEST_STEP_KEYS,
  ASSET_REQUEST_APPROVAL_ACTIONS,
  ASSET_REQUEST_PERMISSIONS,
};
