const AUDIT_ACTIONS = {
  CREATE: "CREATE",
  UPDATE: "UPDATE",
  DELETE: "DELETE",
  ASSIGN: "ASSIGN",
  REMOVE: "REMOVE",
  APPROVE: "APPROVE",
  REJECT: "REJECT",
  CANCEL: "CANCEL",
  COMPLETE: "COMPLETE",
  TRANSACTION: "TRANSACTION",
};

const AUDIT_ENTITY_TYPES = {
  ASSET_REQUEST: "ASSET_REQUEST",
  SPACE: "SPACE",
  SPACE_MEMBER: "SPACE_MEMBER",
  ROLE: "ROLE",
  USER_ROLE: "USER_ROLE",
  WORKFLOW_DEFINITION: "WORKFLOW_DEFINITION",
  WORKFLOW_INSTANCE: "WORKFLOW_INSTANCE",
  INVENTORY_ITEM: "INVENTORY_ITEM",
  INVENTORY_TRANSACTION: "INVENTORY_TRANSACTION",
  PRODUCT: "PRODUCT",
  REPAIR: "REPAIR",
  JOIN_REQUEST: "JOIN_REQUEST",
  WAREHOUSE: "WAREHOUSE",
  USER: "USER",
};

const AUDIT_LOG_PERMISSIONS = {
  VIEW_AUDIT_LOGS: "VIEW_AUDIT_LOGS",
};

module.exports = {
  AUDIT_ACTIONS,
  AUDIT_ENTITY_TYPES,
  AUDIT_LOG_PERMISSIONS,
};
