const INVENTORY_TRANSACTION_TYPES = {
  CREATE: "CREATE",
  ASSIGN_EMPLOYEE: "ASSIGN_EMPLOYEE",
  ASSIGN_MERCHANT: "ASSIGN_MERCHANT",
  RETURN: "RETURN",
  TRANSFER: "TRANSFER",
  STATUS_CHANGE: "STATUS_CHANGE",
  RETIRE: "RETIRE",
  DISPOSE: "DISPOSE",
};

const LEGACY_INVENTORY_TRANSACTION_TYPE_MAP = {
  STOCK_IN: INVENTORY_TRANSACTION_TYPES.CREATE,
  ASSIGN: INVENTORY_TRANSACTION_TYPES.ASSIGN_EMPLOYEE,
  ASSIGNED: INVENTORY_TRANSACTION_TYPES.ASSIGN_EMPLOYEE,
  RETURNED: INVENTORY_TRANSACTION_TYPES.RETURN,
  TRANSFERRED: INVENTORY_TRANSACTION_TYPES.TRANSFER,
  STATUS_CHANGED: INVENTORY_TRANSACTION_TYPES.STATUS_CHANGE,
  RETIRED: INVENTORY_TRANSACTION_TYPES.RETIRE,
  LOST: INVENTORY_TRANSACTION_TYPES.STATUS_CHANGE,
  DAMAGED: INVENTORY_TRANSACTION_TYPES.STATUS_CHANGE,
};

const INVENTORY_TRANSACTION_TYPE_VALUES = [
  ...new Set([
    ...Object.values(INVENTORY_TRANSACTION_TYPES),
    ...Object.keys(LEGACY_INVENTORY_TRANSACTION_TYPE_MAP),
  ]),
];

// Handles normalize inventory transaction type.
const normalizeInventoryTransactionType = (transactionType) => {
  return (
    LEGACY_INVENTORY_TRANSACTION_TYPE_MAP[transactionType] ||
    transactionType
  );
};

// Handles inventory transaction query values with legacy compatibility.
const getInventoryTransactionTypeQueryValues = (transactionType) => {
  const normalizedType = normalizeInventoryTransactionType(
    transactionType
  );
  const legacyValues = Object.entries(
    LEGACY_INVENTORY_TRANSACTION_TYPE_MAP
  )
    .filter(([, value]) => value === normalizedType)
    .map(([key]) => key);

  return [...new Set([normalizedType, ...legacyValues])];
};

const INVENTORY_TRANSACTION_PERMISSIONS = {
  CREATE_INVENTORY_TRANSACTION: "CREATE_INVENTORY_TRANSACTION",
  VIEW_INVENTORY_TRANSACTION: "VIEW_INVENTORY_TRANSACTION",
};

module.exports = {
  INVENTORY_TRANSACTION_TYPES,
  LEGACY_INVENTORY_TRANSACTION_TYPE_MAP,
  INVENTORY_TRANSACTION_TYPE_VALUES,
  normalizeInventoryTransactionType,
  getInventoryTransactionTypeQueryValues,
  INVENTORY_TRANSACTION_PERMISSIONS,
};
