const INVENTORY_STATUS = {
  AVAILABLE: "AVAILABLE",
  ASSIGNED: "ASSIGNED",
  IN_REPAIR: "IN_REPAIR",
  LOST: "LOST",
  RETIRED: "RETIRED",
  DAMAGED: "DAMAGED",
};

const INVENTORY_CONDITION = {
  NEW: "NEW",
  GOOD: "GOOD",
  FAIR: "FAIR",
  DAMAGED: "DAMAGED",
};

const INVENTORY_PERMISSIONS = {
  CREATE_INVENTORY: "CREATE_INVENTORY",
  VIEW_INVENTORY: "VIEW_INVENTORY",
  UPDATE_INVENTORY: "UPDATE_INVENTORY",
  DELETE_INVENTORY: "DELETE_INVENTORY",
};

module.exports = {
  INVENTORY_STATUS,
  INVENTORY_CONDITION,
  INVENTORY_PERMISSIONS,
};