const INVENTORY_TRANSACTION_TYPES = {
  PURCHASE: "PURCHASE",
  ASSIGNMENT: "ASSIGNMENT",
  RETURN: "RETURN",
  TRANSFER: "TRANSFER",
  ADJUSTMENT: "ADJUSTMENT",
  SEND_TO_REPAIR: "SEND_TO_REPAIR",
  REPAIR_RETURN: "REPAIR_RETURN",
  REPAIR_FAILED: "REPAIR_FAILED",
  LOSS: "LOSS",
  DAMAGE: "DAMAGE",
  RETIREMENT: "RETIREMENT",
  STOCK_IN: "STOCK_IN",
  STOCK_OUT: "STOCK_OUT",
  PROCUREMENT: "PROCUREMENT",
  FULFILLMENT: "FULFILLMENT",
  ALLOCATION: "ALLOCATION",
  CREATE: "CREATE",
  ASSIGN_EMPLOYEE: "ASSIGN_EMPLOYEE",
  ASSIGN_MERCHANT: "ASSIGN_MERCHANT",
  STATUS_CHANGE: "STATUS_CHANGE",
  RETIRE: "RETIRE",
  DISPOSE: "DISPOSE",
};

const LEGACY_INVENTORY_TRANSACTION_TYPE_MAP = {
  CREATE: INVENTORY_TRANSACTION_TYPES.STOCK_IN,
  STOCK_IN: INVENTORY_TRANSACTION_TYPES.STOCK_IN,
  STOCK_OUT: INVENTORY_TRANSACTION_TYPES.STOCK_OUT,
  PURCHASED: INVENTORY_TRANSACTION_TYPES.PURCHASE,
  ASSIGN: INVENTORY_TRANSACTION_TYPES.ASSIGNMENT,
  ASSIGNED: INVENTORY_TRANSACTION_TYPES.ASSIGNMENT,
  ASSIGN_EMPLOYEE: INVENTORY_TRANSACTION_TYPES.ASSIGNMENT,
  ASSIGN_MERCHANT: INVENTORY_TRANSACTION_TYPES.ASSIGNMENT,
  RETURNED: INVENTORY_TRANSACTION_TYPES.RETURN,
  TRANSFERRED: INVENTORY_TRANSACTION_TYPES.TRANSFER,
  STATUS_CHANGED: INVENTORY_TRANSACTION_TYPES.ADJUSTMENT,
  SENT_TO_REPAIR: INVENTORY_TRANSACTION_TYPES.SEND_TO_REPAIR,
  REPAIRED: INVENTORY_TRANSACTION_TYPES.REPAIR_RETURN,
  RETIRED: INVENTORY_TRANSACTION_TYPES.RETIREMENT,
  LOST: INVENTORY_TRANSACTION_TYPES.LOSS,
  DAMAGED: INVENTORY_TRANSACTION_TYPES.DAMAGE,
  PROCUREMENT: INVENTORY_TRANSACTION_TYPES.PROCUREMENT,
  FULFILLMENT: INVENTORY_TRANSACTION_TYPES.STOCK_OUT,
};

const INVENTORY_TRANSACTION_TYPE_VALUES = [
  ...new Set([
    ...Object.values(INVENTORY_TRANSACTION_TYPES),
    ...Object.keys(LEGACY_INVENTORY_TRANSACTION_TYPE_MAP),
  ]),
];

// Handles normalize inventory transaction type.
const normalizeInventoryTransactionType = (transactionType) => {
  return (
    LEGACY_INVENTORY_TRANSACTION_TYPE_MAP[transactionType] ||
    transactionType
  );
};

// Handles inventory transaction query values with legacy compatibility.
const getInventoryTransactionTypeQueryValues = (transactionType) => {
  const normalizedType = normalizeInventoryTransactionType(
    transactionType
  );
  const legacyValues = Object.entries(
    LEGACY_INVENTORY_TRANSACTION_TYPE_MAP
  )
    .filter(([, value]) => value === normalizedType)
    .map(([key]) => key);

  return [...new Set([normalizedType, ...legacyValues])];
};

const INVENTORY_TRANSACTION_PERMISSIONS = {
  CREATE_INVENTORY_TRANSACTION: "CREATE_INVENTORY_TRANSACTION",
  VIEW_INVENTORY_TRANSACTION: "VIEW_INVENTORY_TRANSACTION",
};

module.exports = {
  INVENTORY_TRANSACTION_TYPES,
  LEGACY_INVENTORY_TRANSACTION_TYPE_MAP,
  INVENTORY_TRANSACTION_TYPE_VALUES,
  normalizeInventoryTransactionType,
  getInventoryTransactionTypeQueryValues,
  INVENTORY_TRANSACTION_PERMISSIONS,
};
