const NOTIFICATION_CHANNELS = {
  EMAIL: "EMAIL",
};

const NOTIFICATION_STATUS = {
  PENDING: "PENDING",
  SENT: "SENT",
  FAILED: "FAILED",
  SKIPPED: "SKIPPED",
};

const NOTIFICATION_TYPES = {
  ASSET_REQUEST_CREATED: "ASSET_REQUEST_CREATED",
  ASSET_REQUEST_MANAGER_APPROVED: "ASSET_REQUEST_MANAGER_APPROVED",
  ASSET_REQUEST_FULFILLED: "ASSET_REQUEST_FULFILLED",
  ASSET_REQUEST_REJECTED: "ASSET_REQUEST_REJECTED",
  ASSET_REQUEST_CANCELLED: "ASSET_REQUEST_CANCELLED",
  MANUAL: "MANUAL",
};

const NOTIFICATION_PERMISSIONS = {
  SEND_NOTIFICATION: "SEND_NOTIFICATION",
  VIEW_NOTIFICATION: "VIEW_NOTIFICATION",
};

module.exports = {
  NOTIFICATION_CHANNELS,
  NOTIFICATION_STATUS,
  NOTIFICATION_TYPES,
  NOTIFICATION_PERMISSIONS,
};
