const PERMISSIONS = {
  // Space
  CREATE_SPACE: "CREATE_SPACE",
  UPDATE_SPACE: "UPDATE_SPACE",
  VIEW_SPACE: "VIEW_SPACE",
  DELETE_SPACE: "DELETE_SPACE",

  // Users
  CREATE_USER: "CREATE_USER",
  UPDATE_USER: "UPDATE_USER",
  VIEW_USER: "VIEW_USER",
  DELETE_USER: "DELETE_USER",

  // Roles
  CREATE_ROLE: "CREATE_ROLE",
  UPDATE_ROLE: "UPDATE_ROLE",
  VIEW_ROLE: "VIEW_ROLE",
  DELETE_ROLE: "DELETE_ROLE",
  ASSIGN_ROLE: "ASSIGN_ROLE",

  // Warehouse
  CREATE_WAREHOUSE: "CREATE_WAREHOUSE",
  UPDATE_WAREHOUSE: "UPDATE_WAREHOUSE",
  VIEW_WAREHOUSE: "VIEW_WAREHOUSE",
  DELETE_WAREHOUSE: "DELETE_WAREHOUSE",
  // Storage location (alias for warehouse) - added for migration
  CREATE_STORAGE_LOCATION: "CREATE_STORAGE_LOCATION",
  UPDATE_STORAGE_LOCATION: "UPDATE_STORAGE_LOCATION",
  VIEW_STORAGE_LOCATION: "VIEW_STORAGE_LOCATION",
  DELETE_STORAGE_LOCATION: "DELETE_STORAGE_LOCATION",

  // Products
  CREATE_PRODUCT: "CREATE_PRODUCT",
  UPDATE_PRODUCT: "UPDATE_PRODUCT",
  VIEW_PRODUCT: "VIEW_PRODUCT",
  DELETE_PRODUCT: "DELETE_PRODUCT",

  // Inventory
  CREATE_INVENTORY: "CREATE_INVENTORY",
  UPDATE_INVENTORY: "UPDATE_INVENTORY",
  VIEW_INVENTORY: "VIEW_INVENTORY",
  DELETE_INVENTORY: "DELETE_INVENTORY",
  ASSIGN_INVENTORY: "ASSIGN_INVENTORY",

  // Inventory Transactions
  CREATE_INVENTORY_TRANSACTION: "CREATE_INVENTORY_TRANSACTION",
  VIEW_INVENTORY_TRANSACTION: "VIEW_INVENTORY_TRANSACTION",

  // Asset Requests
  CREATE_ASSET_REQUEST: "CREATE_ASSET_REQUEST",
  VIEW_ASSET_REQUEST: "VIEW_ASSET_REQUEST",
  MANAGER_APPROVE_ASSET_REQUEST: "MANAGER_APPROVE_ASSET_REQUEST",
  IT_APPROVE_ASSET_REQUEST: "IT_APPROVE_ASSET_REQUEST",
  REJECT_ASSET_REQUEST: "REJECT_ASSET_REQUEST",
  CANCEL_ASSET_REQUEST: "CANCEL_ASSET_REQUEST",
  FORWARD_ASSET_REQUEST: "FORWARD_ASSET_REQUEST",

  // Repairs
  CREATE_REPAIR: "CREATE_REPAIR",
  VIEW_REPAIR: "VIEW_REPAIR",
  UPDATE_REPAIR: "UPDATE_REPAIR",
  COMPLETE_REPAIR: "COMPLETE_REPAIR",
  CANCEL_REPAIR: "CANCEL_REPAIR",

  // Workflow
  CREATE_WORKFLOW: "CREATE_WORKFLOW",
  VIEW_WORKFLOW: "VIEW_WORKFLOW",
  UPDATE_WORKFLOW: "UPDATE_WORKFLOW",
  DELETE_WORKFLOW: "DELETE_WORKFLOW",
  EXECUTE_WORKFLOW: "EXECUTE_WORKFLOW",

  // Notifications
  SEND_NOTIFICATION: "SEND_NOTIFICATION",
  VIEW_NOTIFICATION: "VIEW_NOTIFICATION",

  // Reports
  VIEW_REPORTS: "VIEW_REPORTS",

  // Audit
  VIEW_AUDIT_LOGS: "VIEW_AUDIT_LOGS",

  // Platform logs
  MANAGE_LOGS: "MANAGE_LOGS",
};

module.exports = {
  PERMISSIONS,
};
