const PRODUCT_ASSET_TYPES = {
  CONSUMABLE: "CONSUMABLE",
  NON_CONSUMABLE: "NON_CONSUMABLE",
};

const PRODUCT_CATEGORIES = {
  LAPTOPS: "LAPTOPS",
  DESKTOPS: "DESKTOPS",
  MONITORS: "MONITORS",
  MOBILES: "MOBILES",
  TABLETS: "TABLETS",
  POS_DEVICES: "POS_DEVICES",
  PRINTERS: "PRINTERS",
  SCANNERS: "SCANNERS",
  ROUTERS_SWITCHES: "ROUTERS_SWITCHES",
  NETWORKING_EQUIPMENT: "NETWORKING_EQUIPMENT",
  PERIPHERALS: "PERIPHERALS",
  ACCESSORIES: "ACCESSORIES",
  SECURITY_DEVICES: "SECURITY_DEVICES",
  SOFTWARE_LICENSES: "SOFTWARE_LICENSES",
  BIOMETRIC_DEVICES: "BIOMETRIC_DEVICES",
  CHARGERS_ADAPTERS: "CHARGERS_ADAPTERS",
  HEADSETS_AUDIO: "HEADSETS_AUDIO",
  STORAGE_DEVICES: "STORAGE_DEVICES",
};

module.exports = {
  PRODUCT_ASSET_TYPES,
  PRODUCT_CATEGORIES,
};