const ROLE_CODES = {
  SPACE_ADMIN: "SPACE_ADMIN",

  INVENTORY_MANAGER: "INVENTORY_MANAGER",

  INVENTORY_APPROVAL: "INVENTORY_APPROVAL",

  APPROVER: "APPROVER",

  VIEWER: "VIEWER",

  AUDITOR: "AUDITOR",

  WAREHOUSE_MANAGER: "WAREHOUSE_MANAGER",
};

module.exports = {
  ROLE_CODES,
};