const ROLE_CODES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  SPACE_ADMIN: "SPACE_ADMIN",
  MEMBER: "MEMBER",
  INVENTORY_MANAGER: "INVENTORY_MANAGER",
  INVENTORY_APPROVAL: "INVENTORY_APPROVAL",
  MANAGER: "MANAGER",
  IT_ADMIN: "IT_ADMIN",
  WAREHOUSE_ADMIN: "WAREHOUSE_ADMIN",
  FOS: "FOS",
  ZONAL_MANAGER: "ZONAL_MANAGER",
  EMPLOYEE: "EMPLOYEE",
  APPROVER: "APPROVER",
  VIEWER: "VIEWER",
  AUDITOR: "AUDITOR",
  WAREHOUSE_MANAGER: "WAREHOUSE_MANAGER",
  STORAGE_LOCATION_MANAGER: "STORAGE_LOCATION_MANAGER",
};

module.exports = {
  ROLE_CODES,
};
