const USER_TYPES = {
  ADMIN: "ADMIN",
  EMPLOYEE: "EMPLOYEE",
  MERCHANT: "MERCHANT",
  OPS: "OPS",
  FOS: "FOS",
  SUPPORT: "SUPPORT",
  FINANCE: "FINANCE",
  WAREHOUSE: "WAREHOUSE",
};

const SIGNUP_USER_TYPES = {
  EMPLOYEE: "EMPLOYEE",
  MERCHANT: "MERCHANT",
};

module.exports = {
  USER_TYPES,
  SIGNUP_USER_TYPES,
};