const USER_TYPES = {
  EMPLOYEE: "EMPLOYEE",
  MERCHANT: "MERCHANT",
};

const SIGNUP_USER_TYPES = {
  EMPLOYEE: "EMPLOYEE",
  MERCHANT: "MERCHANT",
};

module.exports = {
  USER_TYPES,
  SIGNUP_USER_TYPES,
};