const WORKFLOW_ENTITY_TYPES = {
  ASSET_REQUEST: "ASSET_REQUEST",
  REPAIR: "REPAIR",
  INVENTORY_ITEM: "INVENTORY_ITEM",
  PRODUCT: "PRODUCT",
  WAREHOUSE: "WAREHOUSE",
};

const WORKFLOW_STATUS = {
  ACTIVE: "ACTIVE",
  COMPLETED: "COMPLETED",
  CANCELLED: "CANCELLED",
};

const WORKFLOW_STEP_STATUS = {
  PENDING: "PENDING",
  APPROVED: "APPROVED",
  REJECTED: "REJECTED",
  COMPLETED: "COMPLETED",
  SKIPPED: "SKIPPED",
};

const WORKFLOW_ACTIONS = {
  APPROVE: "APPROVE",
  REJECT: "REJECT",
  COMPLETE: "COMPLETE",
  CANCEL: "CANCEL",
  MOVE: "MOVE",
};

const WORKFLOW_PERMISSIONS = {
  CREATE_WORKFLOW: "CREATE_WORKFLOW",
  VIEW_WORKFLOW: "VIEW_WORKFLOW",
  UPDATE_WORKFLOW: "UPDATE_WORKFLOW",
  DELETE_WORKFLOW: "DELETE_WORKFLOW",
  EXECUTE_WORKFLOW: "EXECUTE_WORKFLOW",
};

module.exports = {
  WORKFLOW_ENTITY_TYPES,
  WORKFLOW_STATUS,
  WORKFLOW_STEP_STATUS,
  WORKFLOW_ACTIONS,
  WORKFLOW_PERMISSIONS,
};